services:
  node:
    build:
      context: ./
      dockerfile: docker/nodejs.dockerfile
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./:/app
      - /app/node_modules